metadata.format.version = "1.1"

[versions]
minestom = "2025.07.14-1.21.7"
logback = "1.4.5" # For tests only

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }

logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[bundles]
logback = ["logback-core", "logback-classic"]